name: ステップ 5

on:
  repository_dispatch:
    types:
      - post-merge

permissions:
  contents: read
  actions: write
  issues: write

env:
  STEP_6_FILE: ".github/steps/6-step.md"

jobs:
  find_exercise:
    name: 演習 Issue を検索
    uses: ./.github/workflows/ja-find-exercise-issue.yml
    with:
      issue-title-text: "Git 入門"

  check_step_work:
    name: ステップの作業を確認
    runs-on: ubuntu-latest
    needs: [find_exercise]
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    # Don't check unless at least 10 commits have been made
    if: ${{ github.event.client_payload.branch_commit_count >= 10 }}

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: 最後のコメントを検索
        id: find-last-comment
        uses: peter-evans/find-comment@v3
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          direction: last

      - name: コメントを更新 - 作業確認中
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          file: .github/ja-templates/step-feedback/checking-work.md
          edit-mode: replace

      # START: Check practical exercise

      - name: high score tracker の merge commit を確認
        id: check-for-high-score-tracker-merge-commit
        continue-on-error: true
        uses: actions/github-script@v6
        env:
          commit_messages: ${{ toJson(github.event.client_payload.branch_commit_messages) }}
          keyword: "tracker"
        with:
          script: |
            // Load commit messages and keyword
            const commitMessages = JSON.parse(process.env.commit_messages || "[]");
            let keyword = process.env.keyword || "";
            keyword = keyword.toLowerCase();

            // Check commit messages for keyword
            for (const commit of commitMessages) {
              const message = commit.message.toLowerCase();
              if (message.includes(keyword)) {
                return;
              }
            }
            throw new Error(`No commit message contains the keyword '${keyword}'`);

      - name: calculate level commit を確認
        id: check-calculate-level-commit
        continue-on-error: true
        uses: actions/github-script@v6
        env:
          commit_messages: ${{ toJson(github.event.client_payload.branch_commit_messages) }}
          keyword: "calculate level"
        with:
          script: |
            // Load commit messages and keyword
            const commitMessages = JSON.parse(process.env.commit_messages || "[]");
            let keyword = process.env.keyword || "";
            keyword = keyword.toLowerCase();

            // Check commit messages for keyword
            for (const commit of commitMessages) {
              const message = commit.message.toLowerCase();
              if (message.includes(keyword)) {
                return;
              }
            }
            throw new Error(`No commit message contains the keyword '${keyword}'`);

      - name: Update comment - step results
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          comment-id: ${{ steps.find-last-comment.outputs.comment-id }}
          edit-mode: replace
          file: .github/ja-templates/step-feedback/step-results-table.md
          vars: |
            step_number: 5
            results_table:
              - description: "high score ブランチをマージした"
                passed: ${{ steps.check-for-high-score-tracker-merge-commit.outcome == 'success' }}
              - description: "add level counter ブランチをマージした"
                passed: ${{ steps.check-calculate-level-commit.outcome == 'success' }}

      # END: Check practical exercise

      - name: Fail job if not all checks passed
        if: contains(steps.*.outcome, 'failure')
        run: exit 1

  post_next_step_content:
    name: 次のステップを投稿
    needs: [find_exercise, check_step_work]
    runs-on: ubuntu-latest
    env:
      ISSUE_REPOSITORY: ${{ github.repository }}
      ISSUE_NUMBER: ${{ needs.find_exercise.outputs.issue-number }}

    steps:
      - name: チェックアウト
        uses: actions/checkout@v4

      - name: コメントを作成 - ステップ完了
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/ja-templates/step-feedback/step-finished-prepare-next-step.md
          vars: |
            next_step_number: 6

      - name: コメントを作成 - ステップ本文
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: ${{ env.STEP_6_FILE }}

      - name: コメントを作成 - 進捗待ち
        uses: GrantBirki/comment@v2.1.1
        with:
          repository: ${{ env.ISSUE_REPOSITORY }}
          issue-number: ${{ env.ISSUE_NUMBER }}
          file: .github/ja-templates/step-feedback/watching-for-progress.md

      - name: 現在の workflow を無効化し、次を有効化
        run: |
          gh workflow disable "${{github.workflow}}"
          gh workflow enable "6-step.yml"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
